# Generated by Django 3.1.3 on 2020-11-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='value',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
